### ISSUE TITLE
Question with packages :)

### ISSUE THREAD

**Issue by rphlmr** [Enricopv/turbo-boilerplate#1]
Hi, nice repo :)
Not an issue but a question 🙋‍♂️ 

Does it work if "ui-native" have dependencies like dripsy or other npm packages depending on react-* ?
Of course, I will try when I found 5 minutes 🤓

It takes me hours to build a yarn workspace monorepo (https://github.com/rphlmr/expo-nextjs-monorepo) that works with expo.

My issue (normally solved) was a boot crash on expo ios / android 😅 due to node_module collision conflict.

**Comment by axeldelafosse** [comment]
Hey Raphaël, you might find this interesting: https://github.com/axeldelafosse/expo-next-monorepo-example

**Comment by rphlmr** [comment]
I have to admit that I pick some ideas from your repo 😇
I was in trouble with custom package dependencies collision.
I will pull and try again 🥳

**Comment by Enricopv** [comment]
I'm somewhat new to working metro.config.js so I am having some funny issues with the package. I figured I'd have to go the routes you guys have gone on and will implement similar.

**Comment by Enricopv** [comment]
Hey @rphlmr, I made some updates to the metro configs in `apps/rnative` and `apps/xpo`  inspired by your setup. Works now (on my machine :)). I'm interested to see how it would go for you!
