### ISSUE TITLE
Expo SDK 44 doesn't work.

### ISSUE THREAD

**Issue by Enricopv** [Enricopv/turbo-boilerplate#5]
Getting React invalid hook call error when using SDK 44. I'm working through it now.

**Comment by cloudorbush** [comment]
See this issue https://github.com/expo/expo/issues/6287 to resolve the error.

**Comment by Enricopv** [comment]
I ended up doing just that. Thanks for looking out :)

**Comment by Enricopv** [comment]
That being said, I'm keeping it at sdk 43 because I've running into issues on sdk 44 with @react-navigation/native v6.
