### ISSUE TITLE
Question: simultaneous development of packages/ui and apps/blog and styling

### ISSUE THREAD

**Issue by tejovanthn** [Enricopv/turbo-boilerplate#6]
How do you style the UI components with this setup, and avoid running `yarn install` every time you update any component in the UI package?

**Comment by Enricopv** [comment]
Right now you would just use the standard ways you would style a react or react-native component. I haven't put anything in like styled-components or tailwind for the web apps. 

It shouldn't be running yarn install when you update a UI package, but it does rebuild when you update a file. If you don't want this, and say want to run the blog, then you would do `yarn dev --scope=blog`. This will just run the blog and not anything else.

Doing this will not rebuild the "ui" package when components change in the ui package, but this will also mean you won't see changes in the "blog" app for that component.

`yarn dev` by default runs turbo dev which will run the dev script in each app & package. The "ui" package is set to watch & rebuid with yarn dev.

Using turborepo's `--scope` param is kinda clunky, and I know the maintainer is planning [something different](https://github.com/vercel/turborepo/discussions/105)

**Comment by tejovanthn** [comment]
Got it! Thanks!  :)
