### ISSUE TITLE
replace yarn v1 with pnpm

### ISSUE THREAD

**Issue by ochilliam** [Enricopv/turbo-boilerplate#8]
I couldn't help but to say yarn v1 is super slow.
pnpm recently added [node-linker](https://pnpm.io/npmrc#node-linker) config, pnpm relies on symlinks which metro doesn't support but with the new hoist option it could be used.

so I tried, it went smooth. the problem occurred on metro config saying `packages is undefined`.

**Comment by Enricopv** [comment]
Ahhh I'll try this myself and see how it goes.

**Comment by Enricopv** [comment]
@ochilliam, when you say it went smoothed, what did? Were you able to load up projects?

**Comment by ochilliam** [comment]
I meant replacing pnpm with yarn, last time I checked on another cross-platform workspace it introduced hell of issues. haven't tried other web apps. but was able to build ui-native and bp-request.
I gave up on the above error and should check it again.
could you hint on code what went wrong?
@Enricopv
